---
- name: Add Kubernetes repository
  ansible.builtin.yum_repository:
    name: kubernetes
    description: Kubernetes repository
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.34/rpm/
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.34/rpm/repodata/repomd.xml.key
    enabled: true

- name: Install Kubectl
  ansible.builtin.dnf:
    name:
      - kubectl
    state: present
