- name: Install htpasswd
  ansible.builtin.dnf:
    name: httpd-tools
    state: present

- name: Ensure the auth directory exists
  ansible.builtin.file:
    path: "/etc/platform-registry"
    state: directory
    mode: '0700'

- name: Generate htpasswd file
  ansible.builtin.command:
    cmd: "htpasswd -Bbn {{ registry_user }} {{ registry_password }}"
  register: htpasswd_output
  changed_when: true
  no_log: true

- name: Save htpasswd file
  ansible.builtin.copy:
    content: "{{ htpasswd_output.stdout }}"
    dest: "/etc/platform-registry/htpasswd"
    owner: "root"
    group: "root"
    # insecure but required due to WSL permissions issues
    mode: '0644'
