apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - pvc.yml
  - registry.yml
  - service.yml

secretGenerator:
  - name: registry-auth-secret
    files:
      - htpasswd=htpasswd
    namespace: docker-registry
    type: Opaque
