resources:
  - namespace.yml
  - pvc.yml
  - registry.yml
  - service.yml

secretGenerator:
  - name: registry-auth-secret
    files:
      - htpasswd=/etc/platform-registry/htpasswd
    namespace: docker-registry
    type: Opaque
