apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yml

secretGenerator:  
  - name: registry-pull-secret
    envs:
      - dockerconfig
    namespace: default
    type: kubernetes.io/dockerconfigjson
