resources:
  - service-account.yaml

secretGenerator:  
  - name: registry-pull-secret
    literals:
      - ".dockerconfigjson=$(echo -n '${REGISTRY_USER}:${REGISTRY_PASSWORD}' | base64)"
    namespace: docker-registry
    type: kubernetes.io/dockerconfigjson
