name: Deploy requests

permissions:
  contents: read

on:
  workflow_call:

jobs:
  deploy-requests:
    runs-on: self-hosted
    steps:
      - run: sleep 5

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull latest changes
        if: github.event_name != 'pull_request'
        run: |
          git fetch origin ${{ github.ref }}
          git reset --hard origin/${{ github.ref_name }}
      
      - run: |
          kubectl delete -f generated_python_webservices_requests/ --ignore-not-found=true
          kubectl apply -f generated_python_webservices_requests/ 
        name: Re-deploy requests
