name: Deploy requests

permissions:
  contents: read

on:
  workflow_call:

jobs:
  deploy-requests:
    runs-on: self-hosted
    steps:
      - run: sleep 5

      - name: Checkout repository
        uses: actions/checkout@v4
      
      - run: |
          kubectl delete -f generated_python_webservices_requests/ --ignore-not-found=true
          kubectl apply -f generated_python_webservices_requests/ 
        name: Re-deploy requests
