---
name: Ansible and YAML lint

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    paths:
      - 'ansible/**'
      - 'templates/**'
      - '.github/workflows/**'
      - "generated_webservices_requests/**"
  pull_request:

jobs:
  ansible-yaml-lint:

    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        run: sudo dnf install python3 python3-pip python3-ansible-lint yamllint -y

      - name: Run Ansible Lint
        run: ansible-lint ansible/

      - name: Run yamllint
        run: yamllint .
