---
name: Ansible lint

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    paths:
      - 'ansible/**'
      - .github/workflows/lint_ansible.yml
  pull_request:

jobs:
  ansible-lint:

    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        run: sudo dnf install python3 python3-pip python3-ansible-lint -y

      - name: Run Ansible Lint
        run: ansible-lint ansible/
