---
name: Yaml lint

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    paths:
      - 'ansible/**'
      - 'templates/**'
      - '.github/workflows/**'
      - "generated_webservices_requests/**"
  pull_request:

jobs:
  python-lint:

    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        run: sudo dnf install python3 python3-pip yamllint -y

      - name: Run ruff
        run: yamllint .
